# format = """
# [](#9A348E)\
# $os\
# $username\
# [](bg:#DA627D fg:#9A348E)\
# $directory\
# [](fg:#DA627D bg:#FCA17D)\
# $git_branch\
# $git_status\
# [](fg:#FCA17D bg:#86BBD8)\
# $c\
# $elixir\
# $elm\
# $golang\
# $gradle\
# $haskell\
# $java\
# $julia\
# $nodejs\
# $nim\
# $rust\
# $scala\
# [](fg:#86BBD8 bg:#06969A)\
# $docker_context\
# [](fg:#06969A bg:#33658A)\
# $time\
# [ ](fg:#33658A)\
# """

# [](fg:#df8e1d bg:#40a02b)\ #D2FF72


format = """
[](fg:#d20f39)\
$os\
$username\
[](bg:#333333 fg:#d20f39)\
$directory\
[](bg:#a9ff40 fg:#333333)\
$git_branch\
$git_status\
[](fg:#a9ff40 bg:#d847ef )\

$golang\
$php\
$kotlin\
$python\

$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#d847ef bg:#FBFFE4)\
$docker_context\
[](fg:#FBFFE4 bg:#7287fd)\
$time\
[ ](fg:#7287fd)\
$cmd_duration\
$line_break\
$character"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#d20f39"
style_root = "bg:#d20f39"
format = '[  $user]( $style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#d20f39"
disabled = true      # Disabled by default

[directory]
style = "bg:#333333 fg:#fe640b"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[git_branch]
symbol = ""
style = "bg:#a9ff40 fg:#010101"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#a9ff40 fg:#010101"
format = '[$all_status$ahead_behind ]($style)'


[docker_context]
symbol = " "
style = "bg:#FBFFE4 fg:#010101"
format = '[ $symbol $context ]($style)'

[c]
symbol = " "
style = "bg:#d847ef fg:#010101"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "bg:#d847ef fg:#010101"
format = '[ $symbol ($version) ]($style)'


[elixir]
symbol = " "
style = "bg:#d847ef fg:#010101"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#d847ef fg:#010101"
format = '[ $symbol ($version) ]($style)'


[golang]
symbol = " "
style = "bg:#d847ef fg:#010101"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#d847ef fg:#010101"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#d847ef fg:#010101"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#d847ef fg:#010101"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#d847ef fg:#010101"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#d847ef fg:#010101"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#d847ef fg:#010101"
format = '[ $symbol ($version) ]($style)'

[php]
symbol = ""
style = "bg:#d847ef fg:#010101"
format = '[ $symbol ($version) ]($style)'

[kotlin]
symbol = ""
style = "bg:#d847ef fg:#010101"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "bg:#d847ef fg:#010101"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#d847ef fg:#010101"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#d847ef fg:#010101"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"             # Hour:Minute Format
style = "bg:#7287fd fg:#010101"
format = '[ ♥ $time ]($style)'
